### ISSUE TITLE
piu file not being generated

### ISSUE THREAD

**Issue by patricksouza472** [pumpitupdev/pumptools#59]
# Bug report
I can't find the piu file needed to run Prex 3 anywhere

## Description
I have compiled the latest version of pumptools and sourced the files from Prex 3 arcade disc, checked the game assets checksums which are OK, I have followed the data setup guide but I don't find the piu file anywhere (except for the DOS PIU.EXE file but that won't work). I just wanna set this up to run on my MK9 cab

## Affected games and versions

Prex 3

## Pumptools versions tested
1.12

## OS and hardware specs

* OS: Ubuntu 18.04.6
* CPU: Core 2 Duo E5700 @3.0GHz
* RAM: 4GB
* GPU: Nvidia 8400GS 512MB
* Controllers/IO: MK6 PIUIO

**Comment by voidderef** [comment]
You are looking for the Linux executable that someone manually crafted from the DOS executable. That Linux executable is not provided by pumptools. Due to copyright protection, we can't provide them in the open like on GitHub.

You might find them elsewhere as they could have been redistributed through various channels. The Linux recompiled executables for MK3 games were originally released on a certain "pig stall" site.
